### ISSUE TITLE
Investigate issues with `account_tx` ledgerIndexMin and ledgerIndexMax not matching rippled

### ISSUE THREAD

**Issue by natenichols** [XRPLF/clio#148]
According to an s2 response seen by David Fuelling, account_tx replys w/ `ledger_index_min: 0`, which is incorrect.

Ledger index min should contain the lowest ledger searched, or `ledgerRange.minIndex`, which in the case of a FH server is 32570 iirc.

**Comment by cjcobb23** [comment]
@sappenin we fixed the zero issue, can this be closed now?

**Comment by sappenin** [comment]
@cjcobb23 This is working properly now, thanks for fixing!

(I can't close this issue, but it can be closed)

**Comment by sappenin** [comment]
Note that https://github.com/XRPLF/clio/issues/195 is still a minor issue that I'm still seeing.
