### ISSUE TITLE
ledger dict is missing in the clio response of ledger_data request.

### ISSUE THREAD

**Issue by mounikakun** [XRPLF/clio#219]
Clio response of ledger data is missing 
```
"ledger": {
            "closed": true,
            "ledger_data": "01313BC4016339B8032FC473602AE06E1CAC92745BEE36913847472F5AA0EB8CAAFD52F3EDC0BE5D2622290D00000000000000000000000000000000000000000000000000000000000000002B4B04F65B7565F0A1B1EFB65603149F726E33B2324EF6E6982F0FC0CEF119622A64425E2A6442660A00"
        },
```
Sample ledger_data request(Modify "ledger_index" value based on "complete_ledgers"):
`{
   "method": "ledger_data",
   "params": [
       {
           "binary": true,
           "ledger_index": "20003780",
           "limit": 5
       }
   ]
}
`

**Comment by natenichols** [comment]
This should be fixed in #203

**Comment by mounikakun** [comment]
"closed": true is still missing in "ledger" of Clio response
